### PR TITLE
Added 5 new expansions

### PR DESCRIPTION
**Pull request by AbandonedCart**
Near Pristine Mess
New Pretentious Music
Neurological Pathway Map
Norwegian Prison March
Not Prepared Metaphorically

# What / Why
> n/a

## References
* n/a

### CODE REVIEW

**Comment by AbandonedCart** [comment]
Technically, there are 6. I originally intended "Naughty Panda's Manacles" but noticed someone already had a naughty panda joke and wanted to avoid similarities.

**Comment by lat94** [comment]
Hey, there's a suggestion saying that you should avoid publishing all of your ideas in the same PR:
[If you think of multiple possibilities, please submit them as separate PRs, as we may like some but not others.](https://github.com/npm/npm-expansions#how-to-contribute)

**Comment by AbandonedCart** [comment]
@lat94 There are 1023 pull requests ahead of this one. I'm sure they will understand if you take the day off and allow more than 12 hours to prepare.

**Comment by AbandonedCart** [comment]
Web commits replaced with branches, submitted as:
https://github.com/npm/npm-expansions/pull/2909
https://github.com/npm/npm-expansions/pull/2910
https://github.com/npm/npm-expansions/pull/2911
https://github.com/npm/npm-expansions/pull/2912
https://github.com/npm/npm-expansions/pull/2913
https://github.com/npm/npm-expansions/pull/2914
https://github.com/npm/npm-expansions/pull/2915
https://github.com/npm/npm-expansions/pull/2916

**Pull request closed without merging**
