### PR TITLE
Update expansions.txt

### PR DESCRIPTION
**Pull request by 4i8**

### CODE REVIEW

**Comment by 4i8** [comment]
the Lion king of the jungle

**Comment by Tomyleexrp** [comment]
write access
@Tomyleexrp

**Comment by Tomyleexrp** [comment]
[[ISSUERS]]
address = "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
name = "CasinoCoin"

[[TOKENS]]
issuer = "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
currency = "CSC"
name = "CasinoCoin"
desc = "CasinoCoin (CSC) is a digital currency, developed specifically for the regulated gaming industry."
icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"

[[TOKENS.WEBLINKS]]
url = "https://casinocoin.im"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://casinocoin.info"
type = "website"
title = "Token Info Dashboard"

[[TOKENS.WEBLINKS]]
url = "https://twitter.com/CasinoCoin"
type = "socialmedia"

**Comment by GEOEGII555** [comment]
> [[ISSUERS]]
> address = "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
> name = "CasinoCoin"
> 
> [[TOKENS]]
> issuer = "rCSCManTZ8ME9EoLrSHHYKW8PPwWMgkwr"
> currency = "CSC"
> name = "CasinoCoin"
> desc = "CasinoCoin (CSC) is a digital currency, developed specifically for the regulated gaming industry."
> icon = "https://xumm.app/assets/icons/currencies/ex-csc-3.png"
> 
> [[TOKENS.WEBLINKS]]
> url = "https://casinocoin.im"
> type = "website"
> title = "Official Website"
> 
> [[TOKENS.WEBLINKS]]
> url = "https://casinocoin.info"
> type = "website"
> title = "Token Info Dashboard"
> 
> [[TOKENS.WEBLINKS]]
> url = "https://twitter.com/CasinoCoin"
> type = "socialmedia"

What is this hell

**Comment by hdntc** [comment]
bro what

**Pull request closed without merging**
