### PR TITLE
Neat Pulverised Mush and node push master

### PR DESCRIPTION
**Pull request by thediex09**
Neat Pulverised Mush, Never Push/Pull Mermaids and Nerdy Pac-man

### CODE REVIEW

**Comment by zeke** [comment]
Hey @thediex09 thanks for the submission. I like `Neat Pulverised Mush`, but `node push master` isn't really a thing... If you take that one out I'll merge the mush. :)

**Comment by thediex09** [comment]
OK, i removed it.

**Comment by thediex09** [comment]
I also added Never Push/Pull Mermaids and Nerdy Pac-Man

**Comment by seldo** [comment]
Per the readme guidelines, can you limit each PR to one suggestion? You can submit the others in separate PRs :-)

**Comment by thediex09** [comment]
I tried, but it didn't let me have multiple PRs

**Comment by seldo** [comment]
You will need to create a separate branch for each PR; that's how you make multiple PRs :-)

**Pull request closed without merging**
