### PR TITLE
Node Package Manager

### PR DESCRIPTION
**Pull request by yoyomonem**
It's the true name. I just found that on the Internet.

## References

What "npm" actually stands for ("Node Package Manager")

### CODE REVIEW

**Comment by santi100a** [comment]
There's a little issue - look at [the "No More Please" section of the readme](../#no-more-please)!

**Comment by yoyomonem** [comment]
> @santi100a said:
> There's a little issue - look at [the "No More Please" section of the readme](https://github.com/npm/npm-expansions/#no-more-please)!

WHAT?! But that name's been there ever since npm was created! Oh my God...

**Comment by santi100a** [comment]
@yoyomonem NPM is weird... All I can say is "Welcome to the JavaScript world."

**Comment by yoyomonem** [comment]
> @santi100a said to me:
> npm is weird... All I can say is "Welcome to the JavaScript world."

Well, I'm not new to JavaScript at all, although I do run into errors in my JavaScript.

**Comment by santi100a** [comment]
Oh, I get it! We've all run into errors in our JavaScript.

The lesson? Move to TypeScript, it's never failed me!

**Comment by yoyomonem** [comment]
> @santi100a said:
> Oh, I get it! We've all run into errors in our JavaScript.
> 
> The lesson? Move to TypeScript, it's never failed me!

You could just use `// @ts-check` at the beginning of your JavaScript file so you can automatically get TypeScript's extended strictness in JavaScript files.

**Comment by santi100a** [comment]
Correct, @yoyomonem!
But... are you creating the next big library? Do you want to avoid the need to manually document and write `.d.ts` files yourself? Easy -- just use TypeScript with `--declaration`, it's never failed me!

**Comment by yoyomonem** [comment]
> @santi100a said to me:
> Correct, @yoyomonem! But... are you creating the next big library? Do you want to avoid the need to manually document and write `.d.ts` files yourself? Easy -- just use TypeScript with `--declaration`, it's never failed me!

No thanks. I'd rather use TypeScript without `--declaration`; I won't write any `.d.ts` files.

**Comment by santi100a** [comment]
Will you create `@types` packages then?

**Comment by yoyomonem** [comment]
> @santi100a said:
> Will you create `@types` packages then?

No, I will not create any `@types` packages. I only want to make stuff for everybody to enjoy (other than npm packages; I want to make websites and projects for everybody to enjoy).

**Comment by santi100a** [comment]
Oh, I see! Our approaches differ — you enjoy making websites and other projects **excluding NPM packages**, while I have pretty much abandoned front-end/back-end development to focus on creating simple, general-purpose, platform-independent libraries, like [summation-lib](https://npmjs.com/package/@santi100/summation-lib), which is a TypeScript implementation of the summation operation (Σ), a way to write long sums shortly.

By the way, @yoyomonem, do you make Node.js CLIs?

**Comment by yoyomonem** [comment]
> @santi100a said:
> Oh, I see! Our approaches differ — you enjoy making websites and other projects __excluding npm packages__, while I have pretty much abandoned front-end/back-end development to focus on creating simple, general-purpose, platform-independent libraries, like [summation-lib](https://npmjs.com/package/@santi100/summation-lib), which is a TypeScript implementation of the summation operation (Σ), a way to write long sums shortly.
> 
> By the way, @yoyomonem, do you make Node.js CLIs?

No, I never make Node CLIs. I __use__ Node CLIs.

Oh, and here's an example of a website that I have 100% made: [the-youssef-nasr-company.github.io](https://the-youssef-nasr-company.github.io)

And a fully usable 418 error (I'm A Teapot): [the-youssef-nasr-company.github.io/418(.html)](https://the-youssef-nasr-company.github.io/418)


But, there's some bad news. [`fs`](https://npmjs.com/package/fs) is __GONE.__

**Pull request closed without merging**
