### PR TITLE
Pancakes

### PR DESCRIPTION
**Pull request by victorzimmer**
Neat Pancake Maker

### CODE REVIEW

**Comment by zeke** [comment]
This PR confuses me. Are you a real person, @victorzimmer?

**Comment by victorzimmer** [comment]
Of course I am, what confused you?

—
Victor Zimmer

**Comment by zeke** [comment]
This PR includes 210 commits...

**Comment by victorzimmer** [comment]
I didn't do that, I only committed something about pancakes. GitHub confuses me...

—
Victor Zimmer

**Pull request closed without merging**
