### PR TITLE
That rug really tied the room together.

### PR DESCRIPTION
**Pull request by michaeljwilliams**

### CODE REVIEW

**Comment by zeke** [comment]
The dude abides, but this PR [does not](https://www.npmjs.com/policies/conduct/). The bums lost.

**Comment by michaeljwilliams** [comment]
@zeke Yeah, well, you know, that's just, like, your opinion, man.

Which part of the code are you referring to?

**Comment by zeke** [comment]
We are steering clear of expansions related to bodily functions. That reminds me: I should really remove "nearly pooped myself".

**Comment by michaeljwilliams** [comment]
Fair enough. Thanks for clarifying.

**Pull request closed without merging**
