### PR TITLE
ɹǝʞɐW ǝʌᴉʇɔǝdsɹǝԀ ʍǝN

### PR DESCRIPTION
**Pull request by SpencerStreibel**
Added my own and repositioned my muse, "nuǝɯ pǝɥsᴉꞁod mǝu", such that mine could fit logically into the alphabetical order.

### CODE REVIEW

**Comment by seldo** [comment]
This is extremely clever.

**Comment by SpencerStreibel** [comment]
This suggestion seems to have been removed with the realphabetizing commit. Any reason, a mistake, or am I mistaken?

**Comment by seldo** [comment]
You're right! The pre-publish filter mechanism takes it out because it doesn't technically start with "n".

**Comment by SpencerStreibel** [comment]
Is there a way to fix this? I was really happy with this and it'd be a shame if it wasn't to be merged thanks to not meeting a criteria that it does meet.

**Comment by seldo** [comment]
I'm afraid I don't have time to fix it myself, but if you submit a PR with your suggestion again and a one-line exception for this line: https://github.com/npm/npm-expansions/blob/master/build.js#L12 then it will work and not get blown away by future runs.

**Pull request merged**
