### PR TITLE
Nemetic Pneumatic Mnemenic

### PR DESCRIPTION
**Pull request by Permutatrix**
I found out too late that this was similar to "Noisy Pneumatic Mnemonic". Mine's harder to say five times fast, though.

### CODE REVIEW

**Comment by seldo** [comment]
"Mnemenic" isn't a word. Did you mean Mnemonic?

**Comment by Permutatrix** [comment]
[It actually is](//en.wiktionary.org/wiki/mnemenic), surprisingly enough. I thought it went better with the cadence of the others. It is an adjective, though, and thus makes no grammatical sense.

**Comment by seldo** [comment]
Huh! Today I learned. But still, they have to make sense :-)

**Comment by Permutatrix** [comment]
Okay. Can I propose a modification to an existing entry? I think "nemetic" would be a lot better than "noisy" in the one I mentioned originally.

**Comment by seldo** [comment]
I think we'll leave as-is :-)

**Pull request closed without merging**
