### PR TITLE
Added expansion "Now Pluto Matters"

### PR DESCRIPTION
**Pull request by RalphMarshall**
Seems that even though it's not officially a planet, Pluto is more popular than ever.

### CODE REVIEW

**Comment by seldo** [comment]
Pluto is an excellent idea but we have a lot of "Now"s. Another N word?

**Comment by Tobiaqs** [comment]
"Nowadays Pluto Matters" perhaps?

**Comment by marekhrabe** [comment]
:+1:

**Comment by seldo** [comment]
Waiting for the updated PR :-)

**Pull request closed without merging**
