### PR TITLE
Nice Poutine Meal

### PR DESCRIPTION
**Pull request by sickle2**
"Nice Poutine Meal" added

### CODE REVIEW

**Comment by seldo** [comment]
Too many "Nice" expansions. Try another N word?

**Comment by sickle2** [comment]
"Nifty" ?

**Comment by seldo** [comment]
Sounds good!

**Comment by sickle2** [comment]
Must I close this request, make change, then create a new request ?

**Comment by seldo** [comment]
Nope. Just edit and re-push.

**Pull request merged**
