### PR TITLE
New Programmers Plaything

### PR DESCRIPTION
**Pull request by tomlankhorst**

### CODE REVIEW

**Comment by seldo** [comment]
Add punctuation to "programmer's" or "programmers'" and I'm in :-)

**Comment by mhelgeson** [comment]
NPP? Am I missing something?

**Comment by seldo** [comment]
Uhhhhh. Huh. Yeah. Wow.

**Comment by seldo** [comment]
Deleted from master :-p

**Comment by tomlankhorst** [comment]
Wow! :') excuse me.

**Comment by tomlankhorst** [comment]
Please forgive me and let me try to overcome my stupidity, I've created a
new PR.

**Pull request merged**
