### PR TITLE
Nuclear powered motorcycle

### PR DESCRIPTION
**Pull request by YodaLightsabr**
Added "Nuclear powered motorcycle"

Everyone loves motorcycles, especially when they are nuclear powered.
Nuclear is better than gasoline.

### CODE REVIEW

**Comment by Explosion-Scratch** [comment]
Nice

**Comment by YodaLightsabr** [comment]
Does npm actually monitor this? Lmao

**Comment by Explosion-Scratch** [comment]
I don't think so 😭

**Comment by YodaLightsabr** [comment]
Why do they have it then lol

**Comment by YodaLightsabr** [comment]
Lmfao, nothing has been merged since July. This is stupid.

**Comment by Explosion-Scratch** [comment]
😭 oh well

**Comment by YodaLightsabr** [comment]
Closed because of #3697

**Pull request closed without merging**
