### PR TITLE
added my expansion

### PR DESCRIPTION
**Pull request by ilynivin**
added `Npm cool`

### CODE REVIEW

**Comment by Ghalbeyou** [comment]
it must be containing N,P,M, Npm cool is not one.
it could be: Nice package man

**Comment by ilynivin** [comment]
Ok

**Comment by ilynivin** [comment]
@Ghalbeyou  Is it ok to add Note Package Mate ?

**Comment by ilynivin** [comment]
#4354

**Comment by Ghalbeyou** [comment]
yes

**Pull request closed without merging**
