### PR TITLE
add 'not pictured: midgets'

### PR DESCRIPTION
**Pull request by schisma**
the best phrase

### CODE REVIEW

**Comment by zeke** [comment]
Sorry @schisma, we're steering clear of offensive expansions. Please try again!

**Comment by seldo** [comment]
I think "not pictured: <some other noun>" has potential though.

**Comment by zeke** [comment]
Yes!

**Comment by schisma** [comment]
how about mangoes then?

**Comment by seldo** [comment]
Go for it!

**Comment by isaacs** [comment]
There are indeed no pictures of mangoes on npmjs.com.

**Pull request closed without merging**
