### PR TITLE
Nick's Paperclip Maximizer

### PR DESCRIPTION
**Pull request by Permutatrix**
The [paperclip maximizer](http://wiki.lesswrong.com/wiki/Paperclip_maximizer) is a thought experiment involving an AI that destroys everything in order to produce as many paperclips as possible. It was first proposed by Nick Bostrom, hence "Nick's".

### CODE REVIEW

**Comment by seldo** [comment]
We avoid people's names as that makes it too easy :-)

**Comment by Permutatrix** [comment]
@seldo Too easy to do what?

**Comment by seldo** [comment]
It's too easy to come up with an "N" word that is just somebody's name.

**Comment by Permutatrix** [comment]
@seldo I would tend to disagree, at least in the case of highly relevant names. I guess I'll see if there's another N-word for the paperclip maximizer.

**Comment by seldo** [comment]
Please do!

**Pull request closed without merging**
