### PR TITLE
Add some expansions to expansions.txt

### PR DESCRIPTION
**Pull request by Gum-Joe**
Added the expansions "Now Picture Me" & "Nearly Perfect Moment" (By my non-programmer cousin).

### CODE REVIEW

**Comment by Gum-Joe** [comment]
Just need to remove an expansion.

**Comment by ricordisamoa** [comment]
https://github.com/npm/npm-expansions#how-to-contribute
> If you think of multiple possibilities, please submit them as separate PRs, as we may like some but not others.

**Comment by Gum-Joe** [comment]
Ok

**Comment by Gum-Joe** [comment]
Closing this for now

**Pull request closed without merging**
