### PR TITLE
Never Provoke Marsupials

### PR DESCRIPTION
**Pull request by jmm**
Never is a strong word, but...

* https://www.youtube.com/watch?v=bd165_YTXZQ
* https://www.youtube.com/watch?v=UFWUlObSgn0
* Even the seemingly mild-mannered wombat shouldn't be provoked ar startled. https://en.wikipedia.org/wiki/Wombat#Attacks_on_humans

### CODE REVIEW

**Comment by seldo** [comment]
I like "provoke marsupials" but we have fully 26 expansions that start with "never". Try another N word?

**Comment by jmm** [comment]
Like any of these?:
Nix Provoking Marsupials
Nonsense: Provoking Marsupials
Negatory: Provoking Marsupials
Nay: Provoking Marsupials

**Comment by seldo** [comment]
How about "Needlessly"?

**Comment by jmm** [comment]
Sure. I'll throw out a few more for a last hurrah -- whatever you like I'll PR if you want, or feel free to just go for it.

Nonsensically (don't know why I didn't think of this before)
Nonchalantly (you're not worried about it, even though you probably should be)
Noncommittally (you'll *do* it, but your heart isn't really in it)
Nuisances (enough said)

**Comment by seldo** [comment]
Still waiting for any of these to be pushed :-)

**Comment by jmm** [comment]
Oh, sorry :) I wasn't sure what would make it convenient for you. I think these branches should make it easy to get whichever you want (but if not I can open a new PR or whatever you need):

[Needlessly Provoking Marsupials](https://github.com/npm/npm-expansions/compare/master...jmm:needlessly-provoking-marsupials?expand=1)

[Nonsensically Provoking Marsupials](https://github.com/npm/npm-expansions/compare/master...jmm:nonsensically-provoking-marsupials?expand=1)

[Nonchalantly Provoking Marsupials](https://github.com/npm/npm-expansions/compare/master...jmm:nonchalantly-provoking-marsupials?expand=1)

[Noncommittally Provoking Marsupials](https://github.com/npm/npm-expansions/compare/master...jmm:noncommittally-provoking-marsupials?expand=1)

[Nuisances Provoking Marsupials](https://github.com/npm/npm-expansions/compare/master...jmm:nuisances-provoking-marsupials?expand=1)

Thanks!

**Pull request closed without merging**
