### PR TITLE
ne pas manger !

### PR DESCRIPTION
**Pull request by hu9o**
npm is **not** to be eaten.
It's something the docs aren't really clear about, and I hope I had known this when I started.

### CODE REVIEW

**Comment by seldo** [comment]
That would be "ne mange pas" :-)

**Comment by hu9o** [comment]
The phrase I suggested is *infinitive*, whereas yours is *imperative*.

> The infinitive is used for impersonal commands to an unknown audience, as in warnings, instruction manuals, and recipes. It is used in place of the vous form of the imperative.
(http://french.about.com/od/grammar/a/givingorders.htm)

Indeed, the infinitive is what's expected when it comes to a warning for an inedible package manager. I'd say it's like writing "not to be eaten" on it.

PS: Believe me, French is my mother tongue.

**Comment by seldo** [comment]
Thank you for the lesson! I was trusting Google Translate but it lacks subtle nuances.

**Comment by seldo** [comment]
Please pull latest from master and remove the stray space between "manger" and "!" and re-push.

**Comment by hu9o** [comment]
Never trust Google Translate 100% :)

The rules of written French require that there be a space before an exclamation mark, but I can remove it if you think that'd be better.

**Comment by seldo** [comment]
Either drop the space or, if it wouldn't change the meaning, drop the exclamation point entirely?

**Comment by hu9o** [comment]
Removing the excl. mark doesn't change the meaning, but I find it makes the message clearer (so people understand "not to be eaten" instead of "not to eat").

I dropped the space.

**Comment by seldo** [comment]
There are still conflicts, sorry! Please merge from master and re-push.

**Comment by hu9o** [comment]
Couldn't find this branch when I cloned, so I created a new one: #854

**Comment by hu9o** [comment]
Couldn't find this branch when I cloned, so I created a new one: #854

**Pull request closed without merging**
