### PR TITLE
None Punch Man

### PR DESCRIPTION
**Pull request by vekat**
It's a pretty good show, yes you should watch it.

### CODE REVIEW

**Comment by Permutatrix** [comment]
I had a similar idea. Good thing I searched for it first. I'd like to note that "None-Punch Man", with a hyphen, would probably look less like nonsense to people who haven't heard of the show.

**Comment by vekat** [comment]
Yes, I thought so too. But then the `Avoid hyphenation...` rule scared me a little :sweat_smile:

**Comment by Permutatrix** [comment]
Yeah. I can't claim to be an authority on the matter, but I think you just have to avoid using hyphenation as an _excuse_. Adding a hyphen to a submission that makes sense without it ought to be fine.

**Comment by seldo** [comment]
I have not heard of the show.

**Pull request closed without merging**
