### PR TITLE
NPM Supports Paris

### PR DESCRIPTION
**Pull request by kelthenoble**
I know this isn't NPm usual, But I thought it would like nice, if npm showed some sort of paris support.

### CODE REVIEW

**Comment by kelthenoble** [comment]
@isaacs I'm hoping if you guys don't push this request, it would be nice. If Npm showed some other sort of paris support. Anyway enjoy the rest of your day.

**Comment by seldo** [comment]
Yeah, this repo isn't an appropriate place for political stuff.

**Comment by kelthenoble** [comment]
This isn't meant to be taken as political, I open this for humanity. But yeah, ok nice to know.

**Comment by isaacs** [comment]
Thanks for the sentiment, @kelthenoble.  I agree with @seldo on this one, and would like to elaborate a little bit.

It's not that being generally opposed to the murder of Parisian civilians is a political stance I or npm are afraid of taking.  It's that the issue is complicated, emotionally charged, and timely.

It's tempting for companies to change their logos to blue white and red, or do other surface-level shows of support when something captures the news cycle.  In doing this, they may gain a little bit of temporary buzz.  But it feels a bit shallow and crass to me.

What does npm *actually do* to support Paris?  I mean, beyond making sure that our CDN continues to deliver packages to JavaScripters in western europe.  How *tangible* is our support?

In fact, while I or @seldo or any other wombat may do a variety of things, npm-the-company and npm-the-project are 100% uninvolved.  In that capacity, npm has not earned the right to an opinion, and claiming one would do more for npm than for Paris.  Chances are, it would not change anything at all about the situation.

There's even a chance that this kind of statement could do real harm.  Consider what might happen, a year or two in the future, when some survivor of the attacks sees a reminder on our website, and is suddenly reminded of a personal tragedy.  After all, we wouldn't have any clear point at which to remove the label.  Once established as "supporting" Paris, at what point do we stop?  And would that mean that npm is then making a pro-ISIS statement?  Yikes.

I know that you are trying to do good.  I appreciate your intent.  But items in this list must be lighthearted and timeless.

**Comment by kelthenoble** [comment]
I'm not gonna pretend that i know you, but i do know of you, my favorite words that you produced from your mouth were "zero time for shitbirds."  & I know where your coming from, I get it. Well thanks anyway @isaacs for you time here, giving a proper explanation. Keep pushing the envelope.

**Comment by gregdeane** [comment]
@isaacs A perfectly articulated comment.

**Pull request closed without merging**
