### PR TITLE
adding name "near perfect modules"

### PR DESCRIPTION
**Pull request by arvsr1988**

### CODE REVIEW

**Comment by arvsr1988** [comment]
can someone please accept or reject this pull request?

**Comment by arvsr1988** [comment]
@zeke @aredridel @isaacs @watson can one of you please review this PR?

**Comment by zeke** [comment]
I'm not an owner of this repo any more. I think @seldo is the de facto reviewer.

**Comment by aredridel** [comment]
Same.

**Comment by arvsr1988** [comment]
alright i'm going to close this pr since its been open for too long.

**Pull request closed without merging**
