### PR TITLE
Remove term that doesn't conform to standards

### PR DESCRIPTION
**Pull request by computamike**

### CODE REVIEW

**Comment by missmatsuko** [comment]
This will close #2100

**Comment by computamike** [comment]
It seems that #2100 was closed but the pull request has not been merged in, and the broken epansion is still there...

https://github.com/npm/npm-expansions/blob/e8d73d2650d9ca17bfc04a891272205e7480016d/expansions.txt#L15

Unsure what to do with this patch - can @zeke suggest what I should do?

**Comment by zeke** [comment]
Hi there. 👋🏼  I no longer maintain this project.

Looks like @ethomson is the person who made the most recent updates.

**Comment by ethomson** [comment]
sure!   🙃

**Pull request merged**
